name: Deploy PR env
run-name: ${{ github.actor }} deployed env for PR "${{ github.event.pull_request.title }}"
on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-env:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout PR'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: 'Zip crawler cloud function code'
      run: zip crawler.zip crawler/*

    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/806290897760/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
        service_account: 'terraform@bouldercapacity.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - id: getLowercaseHead
      name: Get lowercase HEAD Ref
      run: INPUT=${{ github.event.pull_request.head.ref }} echo "::set-output name=head::${INPUT,,}"

    - name: Create Terraform workspace for PR
      working-directory: terraform
      run: terraform workspace select ${{steps.getLowercaseHead.outputs.head}} || terraform workspace new ${{steps.getLowercaseHead.outputs.head}}

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate -no-color

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -var="environment=${{steps.getLowercaseHead.outputs.head}}" -var="crawler_names=[\"blockfabrik\"]"
